name: RevampLeaderboards
version: '${version}'
main: me.zypj.revamp.leaderboard.LeaderboardPlugin
authors: [tadeu]
website: https://github.com/zyypj
softdepend: [PlaceholderAPI]
commands:
  lb:
    aliases: [leaderboard]